# Minecraft / mapping / loader versions
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.5

# Mod dependencies
fabric_version=0.116.17+1.21.1

# Mod properties
mod_version=0.31.0-slice31
maven_group=com.realworldmod
archives_base_name=realworldmod

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
